### PR TITLE
fix a bug of autoload pagination

### PR DESCRIPTION
**Pull request by ghost**
just like this:
gif

### CODE REVIEW

**Comment by FaridSafi** [comment]
Hello, is https://github.com/FaridSafi/react-native-gifted-listview/pull/10 a dependency of your pull request ?

**Comment by ghost** [comment]
my code like this,but to the last page does not pause

``` js
_onEndReached(){
    this.refs.listView._onPaginate()
}
<GiftedListView
          ref='listView'
          onEndReached={this._onEndReached}
          onEndReachedThreshold={40}/>
```

**Comment by xubuhang** [comment]
wx20170222-161724 2x
wx20170222-161733 2x
wx20170222-161938 2x
"2" two times in the log 。
@playmusic9

**Comment by xubuhang** [comment]
I solved the problem.
I added a variable to control the addition of data.
wx20170222-164648 2x

**Pull request merged**
