### PR TITLE
headerView was not rendering when refreshable is false

### PR DESCRIPTION
**Pull request by iSimar**

### CODE REVIEW

**Comment by iSimar** [comment]
can you include that in 0.0.7

**Comment by iSimar** [comment]
Hello Farid, can you also publish/bump the version

**Comment by iSimar** [comment]
as I need to merge my branch to master, I have already used 0.0.7:
https://github.com/iSimar/HackerNews-React-Native/commit/ef773595cc1f8adcfb9ac7a88b7458134b1e7cca

**Comment by FaridSafi** [comment]
Hello Simar, sure

**Comment by FaridSafi** [comment]
I released 0.0.7

**Comment by iSimar** [comment]
Thank you

**Comment by FaridSafi** [comment]
FYI, I plan to add support for PullToRefreshViewAndroid in the next version

**Comment by iSimar** [comment]
oh okay, I was actually thinking about implementing that with react-native-gifted-listview too, because I need it for the hacker news android app. 
https://github.com/iSimar/HackerNews-React-Native

**Comment by FaridSafi** [comment]
I will have some availability to work on it tomorrow

**Comment by iSimar** [comment]
okay, looking forward to it. Thank you again, great work.

**Comment by FaridSafi** [comment]
Hello Simar, I published a new version with PullToRefreshViewAndroid support

**Pull request merged**
